[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
padding.x = 5
padding.y = 5
dynamic_title = true
decorations = "none"
startup_mode = "Fullscreen"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[terminal.shell]
program = "/usr/bin/tmux"
